server {
	listen 8080;
	index index.php index.html;
	server_name localhost;
	root /var/www/html/public;
	client_body_temp_path /tmp/nginx/client_temp;
	proxy_temp_path /tmp/nginx/proxy_temp;
	fastcgi_temp_path /tmp/nginx/fastcgi_temp;
	uwsgi_temp_path /tmp/nginx/uwsgi_temp;
	scgi_temp_path /tmp/nginx/scgi_temp;
	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi.conf;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
	location = /health {
		access_log off;
		add_header Content-Type text/plain;
		return 200 'ok';
	}
}
